import { assertAddress, assertHex } from './hex.js';
import { MINT_PUBLIC_SELECTOR, validateIntent, validateSeaDropPublicIntent } from './intent-firewall.js';
import { SEADROP_V1 } from './chains.js';
const API='https://api.opensea.io/api/v2';
function headers({apiKey,token,json=false}={}){const h={accept:'application/json'};if(apiKey)h['x-api-key']=apiKey;if(token)h.authorization=`Bearer ${token}`;if(json)h['content-type']='application/json';return h;}
async function request(path,{method='GET',apiKey=process.env.OPENSEA_API_KEY,token,body,timeoutMs=10000}={}){if(!apiKey&& !path.startsWith('/auth/'))throw new Error('OpenSea API key required');const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),timeoutMs);try{const r=await fetch(`${API}${path}`,{method,headers:headers({apiKey,token,json:body!=null}),body:body==null?undefined:JSON.stringify(body),signal:ctrl.signal,redirect:'error'});const text=await r.text();let payload;try{payload=text?JSON.parse(text):{};}catch{payload={raw:text};}if(!r.ok){const e=new Error(payload?.detail||payload?.message||`OpenSea HTTP ${r.status}`);e.status=r.status;e.payload=payload;throw e;}return payload;}finally{clearTimeout(timer);}}
export async function createInstantApiKey(){return request('/auth/keys',{method:'POST',apiKey:null});}
export async function listDrops({type='upcoming',chains=[],limit=20,cursor,apiKey}={}){const q=new URLSearchParams({type,limit:String(Math.max(1,Math.min(100,Number(limit)||20)))});if(chains?.length)q.set('chains',chains.join(','));if(cursor)q.set('cursor',cursor);return request(`/drops?${q}`,{apiKey});}
export async function getDrop(slug,{apiKey}={}){if(!/^[a-zA-Z0-9][a-zA-Z0-9_-]{0,199}$/.test(String(slug)))throw new Error('invalid drop slug');return request(`/drops/${encodeURIComponent(slug)}`,{apiKey});}
export async function getEligibility(slug,{apiKey=process.env.OPENSEA_API_KEY,token=process.env.OPENSEA_WALLET_JWT}={}){if(!token)throw new Error('OpenSea wallet JWT required for eligibility');return request(`/drops/${encodeURIComponent(slug)}/eligibility`,{apiKey,token});}
export async function buildMintTransaction(slug,{minter,quantity=1,apiKey}={}){assertAddress(minter,'minter');if(!Number.isInteger(Number(quantity))||Number(quantity)<1||Number(quantity)>100)throw new Error('quantity must be 1-100');return request(`/drops/${encodeURIComponent(slug)}/mint`,{method:'POST',apiKey,body:{minter,quantity:Number(quantity)}});}

function isTxObject(x){return x&&typeof x==='object'&&typeof(x.to||x.target)==='string'&&typeof(x.data||x.calldata)==='string';}
export function extractApiTransaction(payload){const seen=new Set();const queue=[payload];while(queue.length){const x=queue.shift();if(!x||typeof x!=='object'||seen.has(x))continue;seen.add(x);if(isTxObject(x)){const to=x.to||x.target,data=x.data||x.calldata,value=x.value??x.valueWei??x.value_wei??'0',chainId=x.chainId??x.chain_id??x.networkId??x.network_id;assertAddress(to,'API transaction target');assertHex(data,'API calldata');return {to,data,value:String(value),chainId:chainId==null?undefined:Number(chainId)};}for(const v of Object.values(x)){if(v&&typeof v==='object')queue.push(v);}}throw new Error('OpenSea response did not contain a transaction object');}

export function classifyOpenSeaPlan({apiPayload,chainId,nftContract,recipient,quantity,allowedTargets=[]}){const tx=extractApiTransaction(apiPayload);tx.chainId=tx.chainId??Number(chainId);const selector=tx.data.slice(0,10).toLowerCase();const base={adapter:'opensea-drops-api',chainId:Number(chainId),nftContract,recipient,quantity:Number(quantity),to:tx.to,data:tx.data,value:String(tx.value),allowedTargets:[...new Set([...(allowedTargets||[]),tx.to])],allowedSelectors:[selector],maxValueWei:String(tx.value),mode:'CONFIRM'};
 if(tx.to.toLowerCase()===SEADROP_V1.toLowerCase()&&selector===MINT_PUBLIC_SELECTOR){const plan={...base,verification:'deterministic',allowedTargets:[SEADROP_V1]};validateSeaDropPublicIntent({...plan,seadrop:SEADROP_V1,payer:recipient},plan);return plan;}
 const explicitlyAllowed=(allowedTargets||[]).map(x=>x.toLowerCase()).includes(tx.to.toLowerCase());const plan={...base,verification:'opaque',allowedTargets:allowedTargets||[],requiresTargetApproval:!explicitlyAllowed,warnings:['OpenSea supplied this transaction. TheDadBot has not proven its target/calldata semantics.','Opaque transactions are confirmation-only and can never execute in AUTO mode.']};if(explicitlyAllowed)validateIntent({...plan,allowedSelectors:[selector]},plan);return plan;}
