import { OPENSEA_FEE_RECIPIENT, SEADROP_V1 } from './chains.js';
import { assertAddress, readWord, wordAddress, wordToAddress, wordToBigInt, wordUint } from './hex.js';
import { MINT_PUBLIC_SELECTOR, validateSeaDropPublicIntent } from './intent-firewall.js';
import { quorumRead, rpcCall } from './rpc.js';

export const GET_PUBLIC_DROP_SELECTOR='0xbc6a629c';
export const GET_ALLOWED_FEE_RECIPIENTS_SELECTOR='0x68632274';
function callData(selector,address){return `${selector}${wordAddress(address)}`;}
export function decodePublicDropResult(result){return {mintPrice:wordToBigInt(readWord(result,0)),startTime:Number(wordToBigInt(readWord(result,1))),endTime:Number(wordToBigInt(readWord(result,2))),maxTotalMintableByWallet:Number(wordToBigInt(readWord(result,3))),feeBps:Number(wordToBigInt(readWord(result,4))),restrictFeeRecipients:wordToBigInt(readWord(result,5))!==0n};}
export function decodeAddressArray(result){const offset=Number(wordToBigInt(readWord(result,0))/32n);const length=Number(wordToBigInt(readWord(result,offset)));const out=[];for(let i=0;i<length;i++)out.push(wordToAddress(readWord(result,offset+1+i)));return out;}
export function encodePublicMint({nftContract,feeRecipient=OPENSEA_FEE_RECIPIENT,minterIfNotPayer='0x0000000000000000000000000000000000000000',quantity}){assertAddress(nftContract,'NFT contract');assertAddress(feeRecipient,'fee recipient');assertAddress(minterIfNotPayer,'minterIfNotPayer');if(!Number.isInteger(Number(quantity))||Number(quantity)<1)throw new Error('quantity must be a positive integer');return `${MINT_PUBLIC_SELECTOR}${wordAddress(nftContract)}${wordAddress(feeRecipient)}${wordAddress(minterIfNotPayer)}${wordUint(quantity)}`;}
export async function readPublicDrop(rpcUrls,nftContract,{seadrop=SEADROP_V1,minAgree}={}){assertAddress(nftContract,'NFT contract');const urls=Array.isArray(rpcUrls)?rpcUrls:[rpcUrls];const [codeQ,dropQ,feesQ]=await Promise.all([quorumRead(urls,'eth_getCode',[seadrop,'latest'],{minAgree}),quorumRead(urls,'eth_call',[{to:seadrop,data:callData(GET_PUBLIC_DROP_SELECTOR,nftContract)},'latest'],{minAgree}),quorumRead(urls,'eth_call',[{to:seadrop,data:callData(GET_ALLOWED_FEE_RECIPIENTS_SELECTOR,nftContract)},'latest'],{minAgree})]);if(!codeQ.value||codeQ.value==='0x'||codeQ.value==='0x0')throw new Error('canonical SeaDrop address has no deployed code');return {...decodePublicDropResult(dropQ.value),allowedFeeRecipients:decodeAddressArray(feesQ.value),quorum:{code:codeQ.agreeing,drop:dropQ.agreeing,feeRecipients:feesQ.agreeing}};}
export function buildPublicMintPlan({chainId,nftContract,quantity,drop,feeRecipient,recipient,payer,seadrop=SEADROP_V1}){const q=Number(quantity);if(!drop)throw new Error('drop state required');const now=Math.floor(Date.now()/1000);const stageStatus=drop.startTime&&now<drop.startTime?'UPCOMING':drop.endTime&&now>drop.endTime?'ENDED':'OPEN';if(drop.maxTotalMintableByWallet&&q>drop.maxTotalMintableByWallet)throw new Error('quantity exceeds public per-wallet cap');const allowed=(drop.allowedFeeRecipients||[]).map(x=>x.toLowerCase());let fee=feeRecipient||OPENSEA_FEE_RECIPIENT;if(drop.restrictFeeRecipients&&!allowed.includes(fee.toLowerCase())){if(!allowed.length)throw new Error('fee recipients are restricted but none were returned');fee=drop.allowedFeeRecipients[0];}const data=encodePublicMint({nftContract,feeRecipient:fee,quantity:q});const value=(BigInt(drop.mintPrice)*BigInt(q)).toString();const plan={adapter:'seadrop-v1-public',verification:'deterministic',mode:'CONFIRM',chainId:Number(chainId),to:seadrop,data,value,nftContract,feeRecipient:fee,recipient,payer,quantity:q,allowedTargets:[seadrop],allowedSelectors:[MINT_PUBLIC_SELECTOR],maxValueWei:value,stageStatus,startTime:drop.startTime,endTime:drop.endTime,createdAt:new Date().toISOString()};validateSeaDropPublicIntent({...plan,seadrop},plan);return plan;}
export async function simulatePlan(rpcUrl,from,plan){return rpcCall(rpcUrl,'eth_call',[{from,to:plan.to,data:plan.data,value:`0x${BigInt(plan.value||0).toString(16)}`},'pending']);}
