const SEADROP='0x00005EA00Ac477B1030CE78506496e8C2dE24bf5';
const OS_FEE='0x0000a26b00c1F0DF003000390027140000fAa719';
const GET_PUBLIC='0xbc6a629c',GET_FEES='0x68632274',MINT_PUBLIC='0x161ac21f';
const ERC721_TRANSFER='0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef';
const CHAINS={1:'Ethereum',8453:'Base',4663:'Robinhood Chain',46630:'Robinhood Testnet',42161:'Arbitrum One',10:'Optimism',137:'Polygon',7777777:'Zora'};
let account=null,chainId=null,currentPlan=null,agentOnline=false;const activity=JSON.parse(localStorage.getItem('thedadbot.activity')||'[]');
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function logEvent(kind,message){activity.unshift({at:new Date().toISOString(),kind,message});activity.splice(100);localStorage.setItem('thedadbot.activity',JSON.stringify(activity));renderActivity();}
function renderActivity(){const el=$('#activity-list');if(!el)return;el.innerHTML=activity.length?activity.map(x=>`<div class="activity-row"><time>${new Date(x.at).toLocaleString()}</time><b>${escapeHtml(x.kind)}</b><span>${escapeHtml(x.message)}</span></div>`).join(''):'<div class="empty-state"><strong>No activity yet</strong><span>Plans, simulations and broadcasts appear here.</span></div>';}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function addr(v){if(!/^0x[0-9a-fA-F]{40}$/.test(v||''))throw new Error('Invalid EVM address');return v;}
function strip(v){return v.replace(/^0x/,'');}function wordAddress(v){return strip(addr(v)).toLowerCase().padStart(64,'0');}function wordUint(v){return BigInt(v).toString(16).padStart(64,'0');}function readWord(hex,i){const s=strip(hex),x=s.slice(i*64,(i+1)*64);if(x.length!==64)throw new Error('Short ABI response');return x;}function wordBig(hex,i){return BigInt('0x'+readWord(hex,i));}function wordAddr(hex,i){return '0x'+readWord(hex,i).slice(24);}function eth(v){const n=BigInt(v);return `${Number(n)/1e18}`.replace(/\.0+$/,'')+' ETH';}
async function request(method,params=[]){if(!window.ethereum)throw new Error('No injected EVM wallet detected');return ethereum.request({method,params});}
function callData(selector,address){return selector+wordAddress(address);}
function decodeAddressArray(hex){const offset=Number(wordBig(hex,0)/32n),len=Number(wordBig(hex,offset)),out=[];for(let i=0;i<len;i++)out.push(wordAddr(hex,offset+1+i));return out;}
async function connect(){const a=await request('eth_requestAccounts');account=a[0];chainId=Number(BigInt(await request('eth_chainId')));$('#metric-wallet').textContent=`${account.slice(0,6)}…${account.slice(-4)}`;$('#metric-chain').textContent=CHAINS[chainId]||`EVM ${chainId}`;$('#connect').textContent=`${account.slice(0,6)}…${account.slice(-4)}`;$('#connect-2').textContent='Wallet connected';try{$('#metric-block').textContent=`block ${Number(BigInt(await request('eth_blockNumber'))).toLocaleString()}`;}catch{}logEvent('WALLET',`Connected ${account} on chain ${chainId}`);return account;}
async function checkAgent(){try{const r=await fetch('http://127.0.0.1:47831/health',{cache:'no-store'});if(!r.ok)throw 0;const j=await r.json();agentOnline=true;$('#agent-button').textContent='Agent online';$('#metric-agent').textContent='Online';$('#automation-status').textContent=JSON.stringify(j,null,2);}catch{agentOnline=false;$('#agent-button').textContent='Agent offline';$('#metric-agent').textContent='Offline';$('#automation-status').textContent='Local agent is offline. Browser-only deterministic SeaDrop mode remains available.';}}
function setView(name){$$('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${name}`));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===name));const titles={overview:'Operations overview',discover:'Drop discovery',mint:'Mint console',wallets:'Wallet security',automation:'Automation',activity:'Activity'};$('#view-title').textContent=titles[name]||'TheDadBot';}
async function buildPlan(){if(!account)await connect();const nft=addr($('#nft-contract').value.trim()),q=Number($('#quantity').value);if(!Number.isInteger(q)||q<1)throw new Error('Quantity must be a positive integer');const fee=addr($('#fee-recipient').value.trim()||OS_FEE);const code=await request('eth_getCode',[SEADROP,'latest']);if(!code||code==='0x'||code==='0x0')throw new Error('Canonical SeaDrop address has no deployed code on this chain');const [dropRaw,feesRaw]=await Promise.all([request('eth_call',[{to:SEADROP,data:callData(GET_PUBLIC,nft)},'latest']),request('eth_call',[{to:SEADROP,data:callData(GET_FEES,nft)},'latest'])]);const drop={mintPrice:wordBig(dropRaw,0),startTime:Number(wordBig(dropRaw,1)),endTime:Number(wordBig(dropRaw,2)),maxPerWallet:Number(wordBig(dropRaw,3)),feeBps:Number(wordBig(dropRaw,4)),restricted:wordBig(dropRaw,5)!==0n,fees:decodeAddressArray(feesRaw)};let chosen=fee;if(drop.restricted&&!drop.fees.map(x=>x.toLowerCase()).includes(chosen.toLowerCase())){if(!drop.fees.length)throw new Error('Fee recipients are restricted but none were returned');chosen=drop.fees[0];}
 const data=MINT_PUBLIC+wordAddress(nft)+wordAddress(chosen)+wordAddress('0x0000000000000000000000000000000000000000')+wordUint(q),value=drop.mintPrice*BigInt(q);const now=Math.floor(Date.now()/1000);const stage=now<drop.startTime?'UPCOMING':drop.endTime&&now>drop.endTime?'ENDED':'OPEN';currentPlan={chainId,to:SEADROP,nft,fee:chosen,quantity:q,data,value,drop,stage};let simulation='not run';if(stage==='OPEN'){await request('eth_call',[{from:account,to:SEADROP,data,value:'0x'+value.toString(16)},'pending']);simulation='passed';}else simulation=stage==='UPCOMING'?'armed; simulation waits for opening':'blocked: stage ended';renderPlan(simulation);$('#send-mint').disabled=stage!=='OPEN';logEvent('PLAN',`${stage} ${q} × ${nft} for ${value} wei`);}
function renderPlan(sim){const p=currentPlan;$('#plan-state').textContent=p.stage==='OPEN'?'Ready for review':p.stage;$('#plan-badge').textContent='deterministic';$('#plan-badge').className='badge good';const ds=$$('#plan-details dd');ds[0].textContent=p.to;ds[1].textContent=p.nft;ds[2].textContent=eth(p.value);ds[3].textContent=p.quantity;ds[4].textContent=`${new Date(p.drop.startTime*1000).toLocaleString()} → ${p.drop.endTime?new Date(p.drop.endTime*1000).toLocaleString():'open'}`;ds[5].textContent=sim;$('#console-log').textContent=JSON.stringify({...p,value:p.value.toString(),drop:{...p.drop,mintPrice:p.drop.mintPrice.toString()}},null,2);}
async function sendMint(){if(!currentPlan)throw new Error('Build and review a plan first');if(Number(BigInt(await request('eth_chainId')))!==currentPlan.chainId)throw new Error('Wallet chain changed after planning');await request('eth_call',[{from:account,to:currentPlan.to,data:currentPlan.data,value:'0x'+currentPlan.value.toString(16)},'pending']);const gas=await request('eth_estimateGas',[{from:account,to:currentPlan.to,data:currentPlan.data,value:'0x'+currentPlan.value.toString(16)}]);const txHash=await request('eth_sendTransaction',[{from:account,to:currentPlan.to,data:currentPlan.data,value:'0x'+currentPlan.value.toString(16),gas}]);$('#console-log').textContent=`Broadcast ${txHash}\nWaiting for receipt and NFT proof…`;logEvent('BROADCAST',txHash);const receipt=await waitReceipt(txHash);const proof=verifyErc721Mint(receipt,currentPlan.nft,account,currentPlan.quantity);$('#console-log').textContent=JSON.stringify({txHash,receiptStatus:receipt.status,postcondition:proof},null,2);$('#plan-state').textContent='Confirmed + NFT proven';logEvent('CONFIRMED',`${txHash}: ${proof.minted} NFT transfer(s) proven`);}
async function waitReceipt(hash){const end=Date.now()+120000;while(Date.now()<end){const r=await request('eth_getTransactionReceipt',[hash]);if(r)return r;await new Promise(r=>setTimeout(r,800));}throw new Error('Receipt timeout; transaction may still be pending');}
function verifyErc721Mint(receipt,nft,recipient,min){if(BigInt(receipt.status||0)!==1n)throw new Error('Transaction reverted');const to=recipient.toLowerCase(),contract=nft.toLowerCase();const rows=(receipt.logs||[]).filter(l=>l.address.toLowerCase()===contract&&(l.topics||[])[0]?.toLowerCase()===ERC721_TRANSFER&&(l.topics||[])[1]==='0x'+'0'.repeat(64)&&('0x'+l.topics[2].slice(-40)).toLowerCase()===to).map(l=>({tokenId:BigInt(l.topics[3]).toString()}));if(rows.length<min)throw new Error('Receipt succeeded but intended ERC-721 mint was not proven');return {ok:true,minted:rows.length,tokens:rows};}
async function loadDrops(){if(!agentOnline)throw new Error('Start the local agent for OpenSea discovery');const type=$('#drop-type').value,chain=$('#drop-chain').value.trim();const u=new URL('http://127.0.0.1:47831/opensea/drops');u.searchParams.set('type',type);if(chain)u.searchParams.set('chains',chain);const r=await fetch(u);const d=await r.json();if(!r.ok)throw new Error(d.error||'Discovery failed');const items=d.drops||d.results||d.data||[];$('#drops').innerHTML=items.length?items.map((x,i)=>{const slug=x.collection_slug||x.slug||x.collection?.slug||'';const name=x.collection_name||x.name||x.collection?.name||slug||`Drop ${i+1}`;const c=x.chain||x.collection?.chain||'';const start=x.start_time||x.startTime||x.stages?.[0]?.startTime;return `<article class="drop-card"><strong>${escapeHtml(name)}</strong><p>${escapeHtml(slug)}</p><div class="meta"><span>${escapeHtml(c||'chain')}</span>${start?`<span>${escapeHtml(new Date(start).toLocaleString())}</span>`:''}</div></article>`;}).join(''):'<div class="empty-state"><strong>No drops returned</strong><span>Try another filter.</span></div>';logEvent('DISCOVER',`Loaded ${items.length} ${type} drops`);}
function safe(fn){return async()=>{try{await fn();}catch(e){$('#console-log').textContent=`${e.name||'Error'}: ${e.message}`;logEvent('BLOCKED',e.message);}};}
$$('.nav-item').forEach(b=>b.onclick=()=>setView(b.dataset.view));$$('[data-jump]').forEach(b=>b.onclick=()=>setView(b.dataset.jump));$('#connect').onclick=safe(connect);$('#connect-2').onclick=safe(connect);$('#agent-button').onclick=checkAgent;$('#plan-mint').onclick=safe(buildPlan);$('#send-mint').onclick=safe(sendMint);$('#load-drops').onclick=safe(loadDrops);$('#clear-log').onclick=()=>{activity.length=0;localStorage.removeItem('thedadbot.activity');renderActivity();};
if(window.ethereum){ethereum.on?.('accountsChanged',()=>location.reload());ethereum.on?.('chainChanged',()=>location.reload());request('eth_accounts').then(async a=>{if(a[0])await connect();}).catch(()=>{});}renderActivity();checkAgent();
